'use strict';
const $ = id => document.getElementById(id);
const esc = v => String(v ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money = n => new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP',maximumFractionDigits:0}).format(n);
const num = v => v === '' || v == null ? null : Number.isFinite(Number(v)) ? Number(v) : null;
const safeUrl = v => {try {const u=new URL(v);return u.protocol==='https:'?u.href:'';}catch{return '';}};
const link = (url,label) => safeUrl(url) ? `<a href="${esc(safeUrl(url))}" target="_blank" rel="noopener noreferrer">${esc(label)} ↗</a>` : '';
function readSaved(){try{return new Set(JSON.parse(localStorage.getItem('next-car-saved')||'[]'));}catch{return new Set();}}
let cars=[], fuel='All', favourites=readSaved(), selected=new Set(), opened=new Set(), loading=false;
const band=c=>`${money(c.low)}–${money(c.high)}`;
const price=c=>c.price!==null?money(c.price):band(c);
function costs(c){
 const miles=num($('mileage').value), petrol=num($('petrol').value), home=num($('home').value), pub=num($('public').value);
 if(miles===null || miles<0)return 'Enter annual miles';
 if(c.eff>0 && home!==null && pub!==null && home>=0 && pub>=0)return `${money(miles/c.eff*home*1.1)} home · ${money(miles/c.eff*pub*1.1)} public / year`;
 if(c.mpg>0 && petrol!==null && petrol>=0)return `${money(miles/c.mpg*4.54609*petrol)} petrol / year`;
 return 'Depends on electric-mile share';
}
function cash(c){const sale=num($('proceeds').value); if(sale===null||sale<0)return '';return c.price!==null?`${money(Math.max(0,c.price-sale))} extra at advertised price`:`${money(Math.max(0,c.low-sale))}–${money(Math.max(0,c.high-sale))} extra at allowance`;} 
function section(title,value){return value?`<div class="detail-section"><h4>${esc(title)}</h4><p>${esc(value)}</p></div>`:'';}
function bootMetric(c){
 if(c.id==='mach-e-er')return {value:'402 + 81 L',note:'Rear boot + separate frunk'};
 if(c.boot===null)return {value:'Load test',note:'Different measurement basis'};
 const gain=c.boot-479;
 return {value:c.boot+' L',note:(gain>=0?'+':'')+gain+' L vs Qashqai'};
}
function card(c){const saved=favourites.has(c.id),standard=/^Standard/.test(c.wheel),boot=bootMetric(c);
 return `<article class="car ${c.rank<=4?'top':''}"><div class="card-main"><div class="card-topline"><span class="tag ${c.fuel==='EV'?'ev':''}">${esc(c.category)} · ${esc(c.fuel)}</span><button class="save ${saved?'saved':''}" data-save="${esc(c.id)}" aria-label="${saved?'Unsave':'Save'} ${esc(c.model)}" aria-pressed="${saved}">${saved?'★':'☆'}</button></div><h3>${esc(c.model)}</h3><p class="years">${esc(c.years)}</p><p class="trim">${esc(c.trim)}</p><div class="metrics"><div class="metric"><span>${c.price===null?'PRICE ALLOWANCE':'ADVERT CHECKED'}</span><strong>${esc(c.price!==null?money(c.price):'£'+(c.low/1000)+'–'+(c.high/1000)+'k')}</strong><small>${c.price!==null&&c.price>Number($('budget').value)?'This example is above your ceiling':'Availability needs reconfirming'}</small></div><div class="metric"><span>BOOT · SEATS UP</span><strong>${esc(boot.value)}</strong><small>${esc(boot.note)}</small></div></div><p class="verdict">${esc(c.verdict)}</p><p class="feature-line"><span class="feature-icon" aria-hidden="true">${standard?'✓':'?'}</span> Heated wheel: <strong>${esc(c.wheel)}</strong></p><p class="note">${c.latest==='Yes'?'Latest major design at research date':c.latest==='No'?'A later major design exists':'Latest-design status needs checking'} · ${esc(c.date)}</p>${cash(c)?`<p class="cash">${esc(cash(c))}</p>`:''}<div class="card-actions"><label><input type="checkbox" data-compare="${esc(c.id)}" ${selected.has(c.id)?'checked':''}> Compare</label>${link(c.url,'View advert / stock')}</div></div><details class="details" data-details="${esc(c.id)}" ${opened.has(c.id)?'open':''}><summary>Comfort, ownership & evidence</summary><div class="details-inner">${section('Seats & comfort',c.seats)}${section('Technology',c.tech)}${section('Why it fits',c.good)}${section('The trade-offs',c.bad)}${section('Space & dimensions',c.bootnote+' '+c.dimensions)}${section('Generation & age',c.update)}${section('Warranty & long-term cover',c.warranty)}<div class="energy"><strong>${esc(costs(c))}</strong><p>Illustrative energy only. Adjust the assumptions above.</p></div>${section('Economy assumptions',c.economy)}${c.fuel==='EV'||c.fuel==='Plug-in hybrid'?section('Range planning',c.range):''}${section('Powertrain & charging',c.charge)}${section('Before buying',c.risks)}${section('Advert evidence',c.evidence)}<div class="source-links">${link(c.url,'Listing / stock')}${link(c.spec,'Specification / reference')}${String(c.extra||'').split(/\s+(?=https:\/\/)/).map((url,i)=>link(url,'Further source '+(i+1))).join('')}</div><p class="note">Researched ${esc(c.date)}. Prices are a dated snapshot, not a live inventory feed.</p></div></details></article>`;
}
function render(){
 document.querySelectorAll('[data-details][open]').forEach(d=>opened.add(d.dataset.details));
 const ceiling=Number($('budget').value), query=$('search').value.trim().toLowerCase();
 const list=cars.filter(c=>(fuel==='All'||c.fuel===fuel)&&(!query||[c.model,c.trim,c.seats,c.tech,c.wheel].join(' ').toLowerCase().includes(query))&&(c.low<=ceiling)&&(!$('shortlist').checked||c.shortlist==='Yes')&&(!$('latest').checked||c.latest==='Yes')&&(!$('verified').checked||(c.price!==null&&c.price<=ceiling))&&(!$('boot').checked||(c.id==='model-y'||c.id==='mach-e-er'||(c.boot!==null&&c.boot>=479)))&&(!$('saved').checked||favourites.has(c.id)));
 list.sort((a,b)=>$('sort').value==='boot'?(b.boot??-1)-(a.boot??-1):$('sort').value==='low'?a.low-b.low:a.rank-b.rank);
 $('results').innerHTML=list.length?list.map(card).join(''):'<div class="empty"><h3>No cars match these filters</h3><p>Try a wider budget or reset your filters.</p><button data-reset>Reset filters</button></div>';
 $('result-count').textContent=`${list.length} ${list.length===1?'contender':'contenders'}`;
 $('filter-note').textContent=$('verified').checked?'Showing a checked price within your ceiling. Reconfirm availability and exact equipment with the dealer.':'Price allowances are shopping estimates. An individual advert can sit above the selected ceiling.';
 document.querySelectorAll('[data-details]').forEach(d=>d.addEventListener('toggle',()=>d.open?opened.add(d.dataset.details):opened.delete(d.dataset.details)));
 updateCompare();
}
function updateCompare(){ $('compare-bar').hidden=!selected.size;$('compare-count').textContent=`${selected.size} of 3 selected`;$('compare-open').disabled=selected.size<2;document.querySelectorAll('[data-compare]').forEach(el=>el.disabled=selected.size>=3&&!selected.has(el.dataset.compare)); }
function showComparison(){const list=cars.filter(c=>selected.has(c.id));const fields=[['Exact version',c=>c.trim],['Advert / allowance',price],['Price evidence',c=>c.evidence],['Extra cash',c=>cash(c)||'Enter sale proceeds above'],['Boot',c=>bootMetric(c).value+' — '+bootMetric(c).note],['Real-world storage',c=>c.bootnote],['Heated wheel',c=>c.wheel],['Seats',c=>c.seats],['Verdict vs Qashqai',c=>c.verdict],['Trade-offs',c=>c.bad],['Energy scenario',costs],['Warranty',c=>c.warranty],['Generation',c=>c.update],['Technology',c=>c.tech],['Range / charging',c=>c.range+' '+c.charge],['Buy checks',c=>c.risks]];
 $('compare-table').innerHTML=`<table><caption class="sr-only">Selected cars comparison</caption><thead><tr><th scope="col">Compare</th>${list.map(c=>`<th scope="col">${esc(c.model)}</th>`).join('')}</tr></thead><tbody>${fields.map(([label,fn])=>`<tr><th scope="row">${esc(label)}</th>${list.map(c=>`<td>${esc(fn(c))}</td>`).join('')}</tr>`).join('')}</tbody></table>`;$('comparison').showModal(); }
function reset(){fuel='All';$('search').value='';$('budget').value='30000';$('sort').value='rank';['shortlist','latest','verified','boot','saved'].forEach(id=>$(id).checked=false);setTabs();render();}
function setTabs(){document.querySelectorAll('[data-fuel]').forEach(b=>{b.classList.toggle('active',b.dataset.fuel===fuel);b.setAttribute('aria-pressed',String(b.dataset.fuel===fuel));});}
document.querySelectorAll('[data-fuel]').forEach(b=>b.addEventListener('click',()=>{fuel=b.dataset.fuel;setTabs();render();}));
['search','budget','sort','shortlist','latest','verified','boot','saved','proceeds','mileage','petrol','home','public'].forEach(id=>$(id).addEventListener('input',render));
$('reset').addEventListener('click',reset);$('results').addEventListener('click',e=>{const btn=e.target.closest('[data-save]');if(btn){const id=btn.dataset.save;favourites.has(id)?favourites.delete(id):favourites.add(id);try{localStorage.setItem('next-car-saved',JSON.stringify([...favourites]));}catch{}render();}if(e.target.closest('[data-reset]'))reset();});
$('results').addEventListener('change',e=>{const id=e.target.dataset.compare;if(!id)return;e.target.checked&&selected.size<3?selected.add(id):selected.delete(id);updateCompare();});
$('compare-open').addEventListener('click',showComparison);$('compare-close').addEventListener('click',()=>$('comparison').close());$('compare-clear').addEventListener('click',()=>{selected.clear();render();});
function parse(data){if(data.schemaVersion!==1||!Array.isArray(data.rows)||data.rows.length<2||!Array.isArray(data.fields))throw new Error('Invalid comparison data');const heads=data.rows[0];for(const h of ['ID','Model','Price allowance low GBP','Price allowance high GBP','Heated steering wheel'])if(!heads.includes(h))throw new Error('Missing source column');const seen=new Set();return data.rows.slice(1).filter(r=>r[0]).map(r=>{const c=Object.fromEntries(data.fields.map(([key,h])=>[key,r[heads.indexOf(h)]??'']));for(const key of ['rank','low','high','price','boot','mpg','eff'])c[key]=num(c[key]);if(!c.id||seen.has(c.id)||!c.model||c.low===null||c.high===null)throw new Error('Invalid car row');seen.add(c.id);return c;});}
function applyData(data,cached=false){cars=parse(data);selected=new Set([...selected].filter(id=>cars.some(c=>c.id===id)));$('screened').innerHTML=(data.screened||[]).map(c=>`<details><summary>${esc(c.model)} <span>${esc(c.verdict)}</span></summary><p>${esc(c.notes)} ${link(c.url,'Reference')}</p></details>`).join('');const dt=new Date(data.syncedAt);$('sync-status').textContent=`${cached?'Cached · ':''}Exported ${Number.isNaN(dt.getTime())?'date unavailable':dt.toLocaleString('en-GB',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'})}`;render();}
async function refresh(){if(loading)return;loading=true;$('refresh').disabled=true;try{const response=await fetch('data.json',{cache:'no-store',signal:AbortSignal.timeout(15000)});if(!response.ok)throw new Error('Export unavailable');const data=await response.json();applyData(data);try{localStorage.setItem('next-car-data',JSON.stringify(data));}catch{}$('error').hidden=true;}catch(error){if(!cars.length){try{applyData(JSON.parse(localStorage.getItem('next-car-data')),true);}catch{}}$('error').textContent=cars.length?'Could not refresh. Showing the last available export; try Refresh again.':'The comparison could not load. Try Refresh or open the spreadsheet.';$('error').hidden=false;if(!cars.length)$('result-count').textContent='Comparison unavailable';}finally{loading=false;$('refresh').disabled=false;}}
$('refresh').addEventListener('click',refresh);document.addEventListener('visibilitychange',()=>{if(!document.hidden)refresh();});setInterval(()=>{if(!document.hidden)refresh();},300000);refresh();
